### ISSUE TITLE
ERROR LOG!

### ISSUE THREAD

**Issue by FristyFlakes** [AndrewLaneX/DiscussUnpinBot#9]
```
start watching logs for service instance discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q
discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q - internal/modules/cjs/loader.js:438
discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q -       throw e;
discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q -       ^
discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q - 
discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q - Error: Cannot find module '/usr/src/app/node_modules/telegraf/lib/index.js'
discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q -     at createEsmNotFoundErr (internal/modules/cjs/loader.js:907:15)
discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q -     at finalizeEsmResolution (internal/modules/cjs/loader.js:900:15)
discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q -     at resolveExports (internal/modules/cjs/loader.js:432:14)
discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q -     at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q -     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q -     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q -     at Module.require (internal/modules/cjs/loader.js:952:19)
discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q -     at require (internal/modules/cjs/helpers.js:88:18)
discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q -     at Object.<anonymous> (/usr/src/app/index.js:3:22)
discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q -     at Module._compile (internal/modules/cjs/loader.js:1063:30) {
discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q -   code: 'MODULE_NOT_FOUND',
discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q -   path: '/usr/src/app/node_modules/telegraf/package.json'
discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q - }
WRN log stream closed for pod discussunpin-d8c256e5-6001-407b-9a7b-faec6efdfa22-7fdd8c6bgdb6q - probably pod restarting error=EOF
```

**Comment by vrumger** [comment]
Make sure you ran `npm install`.
